
let KeyUserId = "userID"
let KeyUnApproved = "unApprovedUserId"
let KeyFirstName = "firstName"
let KeyLastName = "lastName"
let KeyGender = "gender"
let KeyNeighbourHoodId = "neighbourHoodId"
let KeySubCommunityId = "subCommunityId"
let KeyNeighbourHood = "neighbourHood"
let KeySubCommunity = "subCommunity"
let KeyProfileImage = "profileImage"
let KeyResidentSince = "residentSince"
let KeyNationality = "nationality"
let KeyJobTitle = "jobTitle"
let keyAddress = "address"
let KeyExternalChatId = "externalChatId"
let KeyUsername = "username"
let KeyEmail = "email"
let KeyPassword = "password"
let keyInterests = "interest"
let keySkills = "skills"

let KeyProfileStatus = "profileStatus"
let KeyProfileImageData = "profileImageData"
let KeyLoginState = "LoginState"

let KeyIsProfileLoaded = "isProfileLoaded"

let KeyBadge = "SMSBadge"
